repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        name: forbid binary files
        exclude: assets/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [markdown, yaml]

  - repo: local
    hooks:
      - id: format
        name: format Juvix sources
        entry: make -s format
        language: system
        verbose: false
        pass_filenames: false

      - id: typecheck
        name: typecheck Juvix examples
        entry: make -s typecheck
        language: system
        verbose: false
        pass_filenames: false
